-- Version 1 tables from the Submission 3 data dictionary:
-- Material, StaffUser, InventoryTransaction, ImportLog.
-- LowStockAlert and ReorderRequest arrive with Version 2 as migration V2.
-- All fields are NOT NULL unless the data dictionary marks them optional.

CREATE TABLE material (
    material_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_name      VARCHAR(100)  NOT NULL,
    material_type      VARCHAR(50)   NOT NULL
        CONSTRAINT ck_material_type CHECK (material_type IN ('Steel', 'Aluminum', 'Fastener', 'Coating', 'Consumable')),
    unit_of_measure    VARCHAR(20)   NOT NULL,
    quantity_on_hand   DECIMAL(10,2) NOT NULL CONSTRAINT ck_material_qoh CHECK (quantity_on_hand >= 0),
    reorder_threshold  DECIMAL(10,2) NOT NULL CONSTRAINT ck_material_threshold CHECK (reorder_threshold >= 0),
    barcode_value      VARCHAR(50)   NOT NULL CONSTRAINT uq_material_barcode UNIQUE,
    last_updated       TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE staff_user (
    staff_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100) NOT NULL,
    role           VARCHAR(50)  NOT NULL CONSTRAINT ck_staff_role CHECK (role IN ('Stockroom', 'Purchasing', 'Admin')),
    username       VARCHAR(50)  NOT NULL CONSTRAINT uq_staff_username UNIQUE,
    password_hash  VARCHAR(255) NOT NULL
);

CREATE TABLE inventory_transaction (
    transaction_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id            INTEGER       NOT NULL REFERENCES material (material_id),
    transaction_type       VARCHAR(10)   NOT NULL
        CONSTRAINT ck_tx_type CHECK (transaction_type IN ('Check-In', 'Check-Out')),
    quantity               DECIMAL(10,2) NOT NULL CONSTRAINT ck_tx_quantity CHECK (quantity > 0),
    scanned_code           VARCHAR(50)   NOT NULL,
    staff_id               INTEGER       NOT NULL REFERENCES staff_user (staff_id),
    transaction_timestamp  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_tx_material_time ON inventory_transaction (material_id, transaction_timestamp);

CREATE TABLE import_log (
    import_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name             VARCHAR(255) NOT NULL,
    imported_by_staff_id  INTEGER      NOT NULL REFERENCES staff_user (staff_id),
    import_date           TIMESTAMP WITH TIME ZONE NOT NULL,
    records_imported      INTEGER      NOT NULL,
    records_rejected      INTEGER      NOT NULL,
    -- Data dictionary listed VARCHAR(20), but "Completed with Errors" is 21 characters (defect NSI-1, found by tests).
    import_status         VARCHAR(25)  NOT NULL
        CONSTRAINT ck_import_status CHECK (import_status IN ('Completed', 'Completed with Errors', 'Failed'))
);
