-- Version 2 tables from the Submission 3 data dictionary: LowStockAlert and ReorderRequest.
-- All fields are NOT NULL unless the data dictionary marks them optional.

CREATE TABLE low_stock_alert (
    alert_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id          INTEGER       NOT NULL REFERENCES material (material_id),
    triggered_threshold  DECIMAL(10,2) NOT NULL,
    alert_timestamp      TIMESTAMP WITH TIME ZONE NOT NULL,
    status               VARCHAR(20)   NOT NULL
        CONSTRAINT ck_alert_status CHECK (status IN ('Open', 'Acknowledged', 'Resolved')),
    notified_staff_id    INTEGER       NOT NULL REFERENCES staff_user (staff_id)
);
CREATE INDEX ix_alert_material_status ON low_stock_alert (material_id, status);

CREATE TABLE reorder_request (
    request_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id           INTEGER       NOT NULL REFERENCES material (material_id),
    alert_id              INTEGER       REFERENCES low_stock_alert (alert_id),          -- optional: empty for manual requests
    requested_quantity    DECIMAL(10,2) NOT NULL CONSTRAINT ck_reorder_qty CHECK (requested_quantity > 0),
    request_status        VARCHAR(20)   NOT NULL
        CONSTRAINT ck_reorder_status CHECK (request_status IN ('Pending', 'Ordered', 'Closed')),
    created_date          TIMESTAMP WITH TIME ZONE NOT NULL,
    reviewed_by_staff_id  INTEGER       REFERENCES staff_user (staff_id)                -- optional until reviewed
);
CREATE INDEX ix_reorder_status ON reorder_request (request_status, created_date);
